apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: north-south-gateway
  namespace: ingress
spec:
  secretName: north-south-gateway
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: {{ .Values.domain }}
  dnsNames:
  - "{{ .Values.domain }}"
  - "*.{{ .Values.domain }}"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer