apiVersion: v1
kind: Namespace
metadata:
  name: routing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: routing
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: failure-domain.beta.kubernetes.io/zone
      nodeSelector:
        node.wescaleout.cloud/routing: "true"
      tolerations:
      - key: node.wescaleout.cloud/routing
        operator: Equal
        value: "true"
        effect: NoSchedule
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: routing
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: health
      protocol: "TCP"
      port: 30877
      nodePort: 30877
      targetPort: 80
    - name: http
      protocol: "TCP"
      port: 31080
      nodePort: 31080
      targetPort: 80