apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        route53:
          region: {{ .Values.AWS_REGION }}
{{ if and (ne .Values.AWS_ACCESS_KEY_ID "") (ne .Values.AWS_SECRET_ACCESS_KEY "")  }}
          accessKeyIDSecretRef:
            name: letsencrypt-route53
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: letsencrypt-route53
            key: AWS_SECRET_ACCESS_KEY
{{ end }}