{{ if and (ne .Values.AWS_ACCESS_KEY_ID "") (ne .Values.AWS_SECRET_ACCESS_KEY "")  }}
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-route53
  namespace: cert-manager
data:
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY }}
{{ end }}