apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: north-south
  namespace: ingress
spec:
  selector:
    istio: gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.fast.dev.wescaleout.cloud"
    - "*.us.fast.dev.wescaleout.cloud"
    - "*.gcp.fast.dev.wescaleout.cloud"
    - "*.gcp-us.fast.dev.wescaleout.cloud"
    
---
apiVersion: networking.istio.io/v1 
kind: VirtualService
metadata:
  name: home
  namespace: hello-world
spec:
  hosts:
  - hello.fast.dev.wescaleout.cloud
  - hello.us.fast.dev.wescaleout.cloud
  - hello.gcp.fast.dev.wescaleout.cloud
  - hello.gcp-us.fast.dev.wescaleout.cloud
  gateways:
  - ingress/north-south
  http:
  - route:
    - destination:
        host: home.hello-world.svc.cluster.local
        port:
          number: 80