# CURRENTLY UNUSED
# This resource ensures that any load balancers that use listeners (network
# endpoint groups) associated with the istio-gateway know how to health check
# them for liveness/readiness.
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: istio-gateway-listeners
  namespace: ingress
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 15021
        requestPath: /healthz/ready
  targetRef:
    group: ""
    kind: Service
    name: istio-gateway