apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: north-south
  namespace: ingress
spec:
  selector:
    app: north-south-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"